name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  coding_standards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba
      - name: Format
        run: crystal tool format --check
  test:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        crystal:
          - latest
        include:
          - experimental: true
            os: ubuntu-latest
            crystal: nightly
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v5
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install dependencies
        run: shards install --ignore-crystal-version --skip-postinstall --skip-executables
      - name: Run tests
        run: crystal spec -v --error-trace
